### ISSUE TITLE
UnsupportedArchive Error

### ISSUE THREAD

**Issue by Mukhammadsaid19** [divvun/divvunspell-sdk-nodejs#3]
When I first tried to install the package, there was an issue with box-format. 

```
error: failed to get `box-format` as a dependency of package `divvunspell v1.0.0-alpha.5 (https://github.com/divvun/divvunspell?branch=main#1a5fb3d5)`
    ... which satisfies git dependency `divvunspell` (locked to 1.0.0-alpha.5) of package `divvunspell-nodejs v0.1.0 (/home/place2play/tahrirchi-backend/divvunspell-sdk-nodejs/native)`

Caused by:
  failed to load source for dependency `box-format`

Caused by:
  Unable to update https://github.com/bbqsrc/box?branch=master

Caused by:
  failed to find branch `master`
```

I fixed that by running `cargo update`. However, after installation, the package wasn't working. I tried to open a spellchecker archive `.zhfst`. I ran into this problem:

```
Uncaught:
Error: internal error in Neon module: Io("index.xml", Error(Custom(Other, ArcError(UnsupportedArchive("Compression method not supported")))))
    at new SpellChecker (/home/place2play/tahrirchi-backend/divvunspell-sdk-nodejs/lib/index.js:6:20)
```

What might be a problem?

**Comment by Mukhammadsaid19** [comment]
One possible reason for that is about `.hfst` optimized format as all FST files are in this format. Perhaps there was a change in reading `.hfst` optimized format in `box-format`?

**Comment by bbqsrc** [comment]
Oh, it seems there's some out of date dependencies here. Let me have a look.

**Comment by bbqsrc** [comment]
@Mukhammadsaid19 try now.

**Comment by Mukhammadsaid19** [comment]
Thanks, the problem was solved
